#/bin/bash

DATE=$(date +%H-%M-%S)
BACKUP=db-$DATE.sql

#ESTOS DATOS SE INSERTAN COMO PARÁMETROS DEL JOB DE JENKINS
DB_HOST=$1
DB_PASSWORD=$2 #CREDENTIALS ON JENKINS
DB_NAME=$3
AWS_SECRET=$4 #CREDENTIALS ON JENKINS
BUCKET_NAME=$5

#&& QUIERE DECIR QUE SI CUALQUIER SENTENCIA QUE FALLE INVALIDA LAS DEMÁS
mysqldump -u root -h $DB_HOST -p$DB_PASSWORD $DB_NAME > /tmp/$BACKUP && \
export AWS_ACCESS_KEY_ID=AKIA4S5JV5HPEPGOXHAB && \
export AWS_SECRET_ACCESS_KEY=$AWS_SECRET && \
echo "Uploading your $BACKUP backup" && \
aws s3 cp /tmp/db-$DATE.sql s3://$BUCKET_NAME/$BACKUP