version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible
    build:
      context: jenkins-ansible     
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - net
  #NOMBRE DEL SERVICIO (PUEDE SER CUALQUIERA)    
  remote_host:
    #NOMBRE DEL CONTENEDOR (PUEDE SER CUALQUIERA)
    container_name: remote-host
    #EN ESTE CASO NO EXISTE (PERO SÍ EXISTE SU DOCKERFILE ASOCIADO) Y PUEDE SER EL NOMBRE QUE DESEEMOS
    image: remote-host
    #COMO NO EXISTE LE INDICAMOS QUE LO VAMOS A CONSTRUIR
    build:
      #LE INDICAMOS LA RUTA DONDE SE ENCUENTRA EL DOCKERFILE
      context: centos7
    #HACER PERMANENTE EL SCRIPT
    volumes:
      - $PWD/aws-s3.sh:/tmp/script.sh
    networks:
      - net
  #EL NOMBRE DEL SERVICIO EN LA VIDA REAL PUEDE SER UNA IP O DNS
  db_host:
    container_name: db
    image: mysql:5.7
    #DEFINIMOS UNA VARIABLE DE ENTORNO
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - $PWD/db_data:/var/lib/mysql
    networks:
      - net
  # web:
  #   container_name: web
  #   image: ansible-web
  #   build:
  #     context: jenkins-ansible/web
  #   ports:
  #     - "80:80"
  #   networks:
  #     - net
  # git:
  #   container_name: git-server
  #   image: 'gitlab/gitlab-ce:latest'
  #   hostname: 'gitlab.example.com'
  #   ports:
  #     - '8090:80'
  #   volumes:
  #     - '/srv/gitlab/config:/etc/gitlab'
  #     - '/srv/gitlab/logs:/var/log/gitlab'
  #     - '/srv/gitlab/data:/var/opt/gitlab'
  #   networks:
  #     - net
networks:
  net:
